### PR TITLE
Uses ros time for name

### PR DESCRIPTION
**Pull request by tgaspar**

### CODE REVIEW

**Comment by ggorjup** [comment]
As I understand the function, you:
1. Take the provided `ros_t` and and call it `now`
2. Then you compute the difference between the ROS time and the system clock
3. If the difference is larger than 55 seconds, you add 1 hour
4. Then you add the resulting difference back to the ROS time

Questions:
1. What do we gain by this - what was the issue with using the system time directly?
2. Why is 55 seconds the limit?
3. Why add a whole hour to the time offset?
4. What happens if the system time is ahead of ROS time?

**Comment by tgaspar** [comment]
Sorry for the missing description. The question come from the missing context. 

After introducing the `--split-mod` option we noticed that in some rare cases the name of the file is offset by one second. See the `ls -la` below:
```
./data/rosbag/2022-05-11-08-40-00_572.bag
./data/rosbag/2022-05-11-08-45-00_573.bag
./data/rosbag/2022-05-11-08-49-59_574.bag
./data/rosbag/2022-05-11-08-55-00_575.bag
./data/rosbag/2022-05-11-09-00-00_576.bag
./data/rosbag/2022-05-11-09-04-59_577.bag
./data/rosbag/2022-05-11-09-10-00_578.bag
./data/rosbag/2022-05-11-09-15-00_579.bag
```
```
$ rosbag info 2022-05-11-09-04-59_577.bag
path:         2022-05-11-09-04-59_577.bag                                
version:      2.0                                                        
duration:     4:59s (299s)                                               
start:        May 11 2022 09:05:00.00 (1652252700.00)                    
end:          May 11 2022 09:09:59.00 (1652253000.00) 
```

After some digging through the `recorder.cpp` file, I realized that even if we see the following snippet inside the `updateFilenames` function
```cpp
...
    if (options_.append_date)
        parts.push_back(timeToStr(ros::WallTime::now()));
...
```
the `ros::WallTime::now()` does not get used inside the `timeToStr` function:
```cpp
template<class T>
std::string Recorder::timeToStr(T ros_t)
{
    (void)ros_t;
    std::stringstream msg;
    const boost::posix_time::ptime now=
        boost::posix_time::second_clock::local_time();
    boost::posix_time::time_facet *const f=
        new boost::posix_time::time_facet("%Y-%m-%d-%H-%M-%S");
    msg.imbue(std::locale(msg.getloc(),f));
    msg << now;
    return msg.str();
}
```
I **believe** that what happens is that at the time of the call to boost::posix_time::second_clock::local_time() the seconds are just bellow the round (e.g. `59.99` instead of `00`). Therefore, the filename is wrong.

In this PR I changed the `timeToStr` to finally use the provided input. However, I then had to adjust it to local time because the `WallTime::now()` is in UTC.

Since this is a static method I could not pass in a property that gets defined in the class. Therefore I calculate the offset hours at call of `timeToStr`. To avoid the very rare situation where the hour difference would be smaller than it actually is (i.e. `1:59:59.99`) I selected the value `55` as an arbitrarily threshold.

**Comment by ggorjup** [comment]
Thank you for the explanation, now it's much clearer. 
If I understand correctly, the issue is in the potential difference between the ROS clock and the `local_time`, where the local time might be a millisecond slower, which results in a difference between the second values.

Since we are interested only in `"%Y-%m-%d-%H-%M-%S"`, would it make sense to just round the `local_time` to the nearest second instead?

This way, we would:
- Not assume that the function input is in UTC
- Get rid of magic numbers in the function
- Shorten the implementation

At the moment I am not sure how to perform the nearest-second rounding, but a good place to start might be one of these:
- [time_duration.total_microseconds()](https://www.boost.org/doc/libs/1_31_0/libs/date_time/doc/class_time_duration.html) + [round()](https://cplusplus.com/reference/cmath/round/)
- [std::chrono::round()](https://en.cppreference.com/w/cpp/chrono/time_point/round)

**Comment by tgaspar** [comment]
I was thinking about using [round()](https://cplusplus.com/reference/cmath/round/) but as I started digging into it further I noticed it would require some effort with the types and so on. The [std::chrono::round()](https://en.cppreference.com/w/cpp/chrono/time_point/round) seems like suitable. I could have a look at it.

**Comment by fgrcar** [comment]
Cool! Hopefully MARV won't have any troubles with the bags anymore :+1:

**Comment by ggorjup** [comment]
The last revision looks good, approving.

**Pull request merged**
